FROM golang:1.17.0 as builder

WORKDIR /go/src

COPY go.mod go.sum ./
RUN go mod download

ARG CGO_ENABLED=0
ARG GOOS=linux
ARG GOARCH=amd64
ENV GO111MODULE auto

RUN go get github.com/cosmtrek/air
EXPOSE 5000

ENTRYPOINT ["/go/bin/air"]
